import React from "react";
import Head from "next/head";
import Search from "../../src/components/Search/Search";

const SearchIn = () => {
  return (
    <>
      <Head>
        <title>Seller Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>


      <div><Search /></div>
    </>
  );
};

export default SearchIn;
