import React, { useState, useEffect } from "react";
import Head from "next/head";

import BusinessProfileComp from "../../src/components/BusinessProfile/BusinessProfileComp";

function useWindowSize() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      function handleResize() {
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }
      window.addEventListener("resize", handleResize);
      handleResize();
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []);
  return windowSize;
}

const BusinessProfile = () => {
  const size = useWindowSize();

  return (
    <>
      <Head>
        <title>Business Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>

      <div>
        <div style={{ marginTop: "20px" }}>
          <BusinessProfileComp />
        </div>
      </div>
    </>
  );
};

export default BusinessProfile;
