import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Dashboard from "../src/components/Dashboard/dashboard"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Seller Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>

      <main><Dashboard/></main>
    </div>
  );
}
