import React from "react";
import Head from "next/head";

import System from "../../src/components/System/System"

const SellerSystem = () => {
  return (
    <>
      <Head>
        <title>Seller Panel System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/LogoMini.png" />
      </Head>

      <div><System/></div>
    </>
  );
};

export default SellerSystem;
